"""Build the ingredient_aliases table with common synonyms and translations."""

from __future__ import annotations

import logging

from scripts._db import SyncSession

from app.models.dietary_ingredient import DietaryIngredient  # noqa: F401
from app.models.ingredient_alias import IngredientAlias  # noqa: F401
from app.database import Base  # noqa: F401

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
log = logging.getLogger(__name__)

# (alias, canonical_name, language)
ALIASES: list[tuple[str, str, str]] = [
    # Cheese aliases
    ("parmesan", "parmesan cheese", "en"),
    ("parm", "parmesan cheese", "en"),
    ("parmigiano", "parmesan cheese", "it"),
    ("parmigiano reggiano", "parmesan cheese", "it"),
    ("cheddar", "cheddar cheese", "en"),
    ("gouda", "gouda cheese", "en"),
    ("emmental", "emmental cheese", "en"),
    ("gruyere", "gruyere cheese", "en"),
    ("swiss", "swiss cheese", "en"),
    ("blue cheese", "blue cheese", "en"),
    ("bleu cheese", "blue cheese", "en"),
    ("gorgonzola", "gorgonzola", "en"),
    ("roquefort", "roquefort", "en"),
    ("feta", "feta cheese", "en"),
    ("brie cheese", "brie", "en"),
    ("camembert cheese", "camembert", "en"),
    ("pecorino", "aged cheese", "en"),
    ("pecorino romano", "aged cheese", "en"),
    ("goat cheese", "goat cheese, fresh", "en"),
    ("chevre", "goat cheese, fresh", "fr"),
    ("mozzarella cheese", "mozzarella", "en"),
    ("mozz", "mozzarella", "en"),
    # Vegetable aliases (British/Australian English)
    ("aubergine", "eggplant", "en"),
    ("courgette", "zucchini", "en"),
    ("capsicum", "bell pepper", "en"),
    ("rocket", "arugula", "en"),
    ("coriander", "cilantro", "en"),
    ("coriander leaves", "cilantro", "en"),
    ("spring onion", "spring onion (white)", "en"),
    ("scallion", "spring onion (white)", "en"),
    ("green onion", "spring onion (white)", "en"),
    ("green olive", "olives", "en"),
    ("green olives", "olives", "en"),
    ("black olive", "olives", "en"),
    ("black olives", "olives", "en"),
    ("kalamata olive", "olives", "en"),
    ("kalamata olives", "olives", "en"),
    ("beetroot", "beet", "en"),
    ("swede", "turnip", "en"),
    ("sweetcorn", "corn", "en"),
    ("maize", "corn", "en"),
    ("courgettes", "zucchini", "en"),
    ("peppers", "bell pepper", "en"),
    ("red pepper", "bell pepper", "en"),
    ("green pepper", "bell pepper", "en"),
    ("yellow pepper", "bell pepper", "en"),
    ("orange pepper", "bell pepper", "en"),
    ("red bell pepper", "bell pepper", "en"),
    ("yellow bell pepper", "bell pepper", "en"),
    ("green bell pepper", "bell pepper", "en"),
    ("orange bell pepper", "bell pepper", "en"),
    ("sweet pepper", "bell pepper", "en"),
    ("sweet peppers", "bell pepper", "en"),
    ("bell peppers", "bell pepper", "en"),
    ("baby spinach", "spinach", "en"),
    ("spinach leaves", "spinach", "en"),
    ("romaine", "lettuce", "en"),
    ("romaine lettuce", "lettuce", "en"),
    ("iceberg lettuce", "lettuce", "en"),
    ("iceberg", "lettuce", "en"),
    ("butter lettuce", "lettuce", "en"),
    ("bibb lettuce", "lettuce", "en"),
    ("little gem", "lettuce", "en"),
    ("mixed greens", "mixed salad greens", "en"),
    ("salad greens", "mixed salad greens", "en"),
    ("mixed salad", "mixed salad greens", "en"),
    ("leafy greens", "mixed salad greens", "en"),
    ("mesclun", "mixed salad greens", "en"),
    ("spring mix", "mixed salad greens", "en"),
    ("baby greens", "mixed salad greens", "en"),
    ("microgreen", "microgreens", "en"),
    ("micro greens", "microgreens", "en"),
    ("sprouts", "microgreens", "en"),
    ("alfalfa sprouts", "microgreens", "en"),
    ("bean sprouts", "microgreens", "en"),
    ("button mushrooms", "mushroom", "en"),
    ("button mushroom", "mushroom", "en"),
    ("mushrooms", "mushroom", "en"),
    ("portobello", "mushroom", "en"),
    ("portobello mushroom", "mushroom", "en"),
    ("portobello mushrooms", "mushroom", "en"),
    ("shiitake", "mushroom", "en"),
    ("shiitake mushroom", "mushroom", "en"),
    ("shiitake mushrooms", "mushroom", "en"),
    ("cremini", "mushroom", "en"),
    ("cremini mushroom", "mushroom", "en"),
    ("cremini mushrooms", "mushroom", "en"),
    ("oyster mushroom", "mushroom", "en"),
    ("oyster mushrooms", "mushroom", "en"),
    ("champignon", "mushroom", "fr"),
    # Common vegetable plurals and varieties. The head-noun fallback
    # handles many compound forms ("cherry tomato" -> "tomato"), but bare
    # plurals like "tomatoes" can't be resolved that way — they need
    # explicit aliases.
    ("tomatoes", "tomato", "en"),
    ("cherry tomatoes", "tomato", "en"),
    ("cherry tomato", "tomato", "en"),
    ("grape tomatoes", "tomato", "en"),
    ("plum tomatoes", "tomato", "en"),
    ("roma tomatoes", "tomato", "en"),
    ("onions", "onion", "en"),
    ("red onion", "onion", "en"),
    ("red onions", "onion", "en"),
    ("white onion", "onion", "en"),
    ("yellow onion", "onion", "en"),
    ("brown onion", "onion", "en"),
    ("potatoes", "potato", "en"),
    ("baby potatoes", "potato", "en"),
    ("new potatoes", "potato", "en"),
    ("roast potatoes", "potato", "en"),
    ("mashed potato", "potato", "en"),
    ("mashed potatoes", "potato", "en"),
    ("sweet potatoes", "sweet potato", "en"),
    ("yam", "sweet potato", "en"),
    ("yams", "sweet potato", "en"),
    ("carrots", "carrot", "en"),
    ("baby carrots", "carrot", "en"),
    ("cucumbers", "cucumber", "en"),
    ("zucchinis", "zucchini", "en"),
    ("eggplants", "eggplant", "en"),
    ("aubergines", "eggplant", "en"),
    ("avocados", "avocado", "en"),
    ("radishes", "radish", "en"),
    ("beets", "beet", "en"),
    ("celery stalks", "celery", "en"),
    ("garlic clove", "garlic", "en"),
    ("garlic cloves", "garlic", "en"),
    ("shallots", "shallot", "en"),
    ("leeks", "leek", "en"),
    ("chilies", "chili pepper", "en"),
    ("chillies", "chili pepper", "en"),
    ("jalapeno", "chili pepper", "en"),
    ("jalapenos", "chili pepper", "en"),
    ("serrano", "chili pepper", "en"),
    ("habanero", "chili pepper", "en"),
    # Meat aliases
    ("beef", "beef, fresh", "en"),
    ("steak", "beef, fresh", "en"),
    ("pork", "pork, fresh", "en"),
    ("pork chop", "pork, fresh", "en"),
    ("pork loin", "pork, fresh", "en"),
    ("chicken breast", "chicken", "en"),
    ("chicken thigh", "chicken", "en"),
    ("chicken leg", "chicken", "en"),
    ("chicken wing", "chicken", "en"),
    ("chicken drumstick", "chicken", "en"),
    ("turkey breast", "turkey", "en"),
    ("minced beef", "ground beef", "en"),
    ("ground meat", "ground beef", "en"),
    ("mince", "ground beef", "en"),
    ("prosciutto crudo", "prosciutto", "it"),
    ("parma ham", "prosciutto", "en"),
    ("guanciale", "pancetta", "en"),
    ("pork sausage", "sausage, fresh", "en"),
    ("cocktail sausage", "sausage, cured", "en"),
    # Fish aliases
    ("salmon", "salmon, fresh", "en"),
    ("tuna", "tuna, fresh", "en"),
    ("tinned tuna", "tuna, canned", "en"),
    ("canned tuna", "tuna, canned", "en"),
    ("tinned sardines", "sardines, canned", "en"),
    ("canned sardines", "sardines, canned", "en"),
    ("smoked salmon", "salmon, smoked", "en"),
    ("lox", "salmon, smoked", "en"),
    ("prawns", "shrimp", "en"),
    # Plant-based milk/cream/butter aliases
    ("coconut cream", "coconut cream", "en"),
    ("coconut yoghurt", "coconut yogurt", "en"),
    ("oat cream", "oat milk", "en"),
    ("soya milk", "soy milk", "en"),
    ("almond cream", "almond milk", "en"),
    ("rice cream", "rice milk", "en"),
    ("cashew cream", "cashew milk", "en"),
    ("hemp cream", "hemp milk", "en"),
    # Dairy aliases
    ("whole milk", "milk", "en"),
    ("skim milk", "milk", "en"),
    ("semi-skimmed milk", "milk", "en"),
    ("heavy cream", "cream", "en"),
    ("double cream", "cream", "en"),
    ("single cream", "cream", "en"),
    ("whipping cream", "cream", "en"),
    ("natural yogurt", "yogurt", "en"),
    ("greek yogurt", "yogurt", "en"),
    ("plain yogurt", "yogurt", "en"),
    ("creme fraiche", "sour cream", "en"),
    # Grain/carb aliases
    ("white rice", "rice", "en"),
    ("brown rice", "rice", "en"),
    ("basmati rice", "rice", "en"),
    ("jasmine rice", "rice", "en"),
    ("spaghetti", "pasta", "en"),
    ("spaghetti noodle", "pasta", "en"),
    # "penne" -> "penne pasta" and "macaroni" (a canonical now) are seeded by
    # load_curated; both previously pointed at "pasta", which is not a
    # canonical, so those rows were always skipped here.
    ("fusilli", "pasta", "en"),
    ("linguine", "pasta", "en"),
    ("fettuccine", "pasta", "en"),
    ("tagliatelle", "pasta", "en"),
    ("rigatoni", "pasta", "en"),
    ("noodles", "pasta", "en"),
    ("white bread", "bread", "en"),
    ("wholemeal bread", "bread", "en"),
    ("whole wheat bread", "bread", "en"),
    ("baguette", "bread", "en"),
    ("ciabatta", "bread", "en"),
    ("sourdough", "sourdough bread", "en"),
    ("porridge", "oats", "en"),
    ("oatmeal", "oats", "en"),
    ("rolled oats", "oats", "en"),
    # Egg aliases
    ("eggs", "egg", "en"),
    ("boiled egg", "egg", "en"),
    ("boiled eggs", "egg", "en"),
    ("scrambled egg", "egg", "en"),
    ("scrambled eggs", "egg", "en"),
    ("fried egg", "egg", "en"),
    ("fried eggs", "egg", "en"),
    ("omelette", "egg", "en"),
    ("omelet", "egg", "en"),
    ("poached egg", "egg", "en"),
    ("poached eggs", "egg", "en"),
    # Nut/seed aliases
    ("almond", "almonds", "en"),
    ("walnut", "walnuts", "en"),
    ("cashew", "cashews", "en"),
    ("pistachio", "pistachios", "en"),
    ("pistachio nut", "pistachios", "en"),
    ("hazelnut", "hazelnuts", "en"),
    ("pecan", "pecans", "en"),
    ("peanut", "peanuts", "en"),
    ("groundnut", "peanuts", "en"),
    # Condiment/sauce aliases
    ("ketchup", "ketchup", "en"),
    ("catsup", "ketchup", "en"),
    ("tomato ketchup", "ketchup", "en"),
    ("dijon mustard", "mustard", "en"),
    ("wholegrain mustard", "mustard", "en"),
    ("mayo", "mayonnaise", "en"),
    ("soya sauce", "soy sauce", "en"),
    ("shoyu", "soy sauce", "ja"),
    ("tamari", "soy sauce", "ja"),
    ("balsamic", "balsamic vinegar", "en"),
    ("ACV", "apple cider vinegar", "en"),
    ("extra virgin olive oil", "olive oil", "en"),
    ("EVOO", "olive oil", "en"),
    ("rapeseed oil", "rapeseed oil", "en"),
    ("canola oil", "rapeseed oil", "en"),
    ("cooking oil", "vegetable oil", "en"),
    # Tahini and sesame-based dressings — histamine profile is dominated
    # by the tahini/sesame base, so route to that canonical.
    ("tahini dressing", "tahini", "en"),
    ("tahini sauce", "tahini", "en"),
    ("sesame paste", "tahini", "en"),
    ("sesame dressing", "sesame seeds", "en"),
    # Other common dressings — map to closest sensible canonical.
    ("vinaigrette", "vinegar", "en"),
    ("balsamic dressing", "balsamic vinegar", "en"),
    ("balsamic vinaigrette", "balsamic vinegar", "en"),
    ("italian dressing", "olive oil", "en"),
    ("french dressing", "olive oil", "en"),
    ("olive oil dressing", "olive oil", "en"),
    ("lemon dressing", "lemon", "en"),
    ("yogurt dressing", "yogurt", "en"),
    ("yoghurt dressing", "yogurt", "en"),
    ("mustard dressing", "mustard", "en"),
    ("honey mustard", "mustard", "en"),
    ("honey mustard dressing", "mustard", "en"),
    # Sauces that share a dominant canonical.
    ("marinara", "tomato sauce", "en"),
    ("marinara sauce", "tomato sauce", "en"),
    ("pasta sauce", "tomato sauce", "en"),
    ("passata", "tomato sauce", "en"),
    ("hummus dip", "chickpeas", "en"),
    # Fruit aliases
    ("strawberries", "strawberry", "en"),
    ("blueberries", "blueberry", "en"),
    ("raspberries", "raspberry", "en"),
    ("blackberries", "blackberry", "en"),
    ("cherries", "cherry", "en"),
    ("grapes", "grape", "en"),
    ("oranges", "orange", "en"),
    ("lemons", "lemon", "en"),
    ("limes", "lime", "en"),
    ("dates", "date", "en"),
    ("figs", "fig", "en"),
    ("raisins", "raisin", "en"),
    ("sultanas", "raisin", "en"),
    ("dried cranberries", "cranberry", "en"),
    ("plantain", "banana", "en"),
    ("apples", "apple", "en"),
    ("pears", "pear", "en"),
    ("peaches", "peach", "en"),
    ("apricots", "apricot", "en"),
    ("plums", "plum", "en"),
    ("nectarines", "nectarine", "en"),
    ("mangoes", "mango", "en"),
    ("mangos", "mango", "en"),
    ("pineapples", "pineapple", "en"),
    ("avocadoes", "avocado", "en"),
    ("watermelons", "watermelon", "en"),
    ("kiwis", "kiwi", "en"),
    ("kiwifruit", "kiwi", "en"),
    ("bananas", "banana", "en"),
    ("melons", "melon", "en"),
    # Legume aliases
    ("red lentils", "lentils", "en"),
    ("green lentils", "lentils", "en"),
    ("brown lentils", "lentils", "en"),
    ("puy lentils", "lentils", "en"),
    ("garbanzo beans", "chickpeas", "en"),
    ("hummus", "chickpeas", "en"),
    ("cannellini beans", "white beans", "en"),
    ("navy beans", "white beans", "en"),
    ("great northern beans", "white beans", "en"),
    ("lima beans", "white beans", "en"),
    ("edamame beans", "edamame", "en"),
    # Spice/herb aliases
    ("chilli", "chili powder", "en"),
    ("chili", "chili powder", "en"),
    ("red pepper flakes", "chili flakes", "en"),
    ("fresh basil", "basil", "en"),
    ("dried basil", "basil", "en"),
    ("fresh thyme", "thyme", "en"),
    ("fresh rosemary", "rosemary", "en"),
    ("fresh mint", "mint", "en"),
    ("fresh dill", "dill", "en"),
    ("flat leaf parsley", "parsley", "en"),
    ("curly parsley", "parsley", "en"),
    ("fresh parsley", "parsley", "en"),
    # Beverage aliases
    ("espresso", "coffee", "en"),
    ("cappuccino", "coffee", "en"),
    ("latte", "coffee", "en"),
    ("americano", "coffee", "en"),
    ("decaf", "coffee", "en"),
    ("matcha", "green tea", "en"),
    ("chamomile tea", "herbal tea", "en"),
    ("peppermint tea", "herbal tea", "en"),
    ("rooibos", "herbal tea", "en"),
    # French translations (Luxembourg context)
    ("poulet", "chicken", "fr"),
    ("dinde", "turkey", "fr"),
    ("boeuf", "beef, fresh", "fr"),
    ("agneau", "lamb", "fr"),
    ("porc", "pork, fresh", "fr"),
    ("veau", "veal", "fr"),
    ("canard", "duck", "fr"),
    ("lapin", "rabbit", "fr"),
    ("jambon", "ham", "fr"),
    ("saucisse", "sausage, fresh", "fr"),
    ("saucisson", "salami", "fr"),
    ("lardons", "bacon", "fr"),
    ("fromage", "cheese", "fr"),
    ("beurre", "butter", "fr"),
    ("lait", "milk", "fr"),
    ("creme", "cream", "fr"),
    ("creme fraiche", "sour cream", "fr"),
    ("yaourt", "yogurt", "fr"),
    ("oeuf", "egg", "fr"),
    ("oeufs", "egg", "fr"),
    ("pain", "bread", "fr"),
    ("riz", "rice", "fr"),
    ("pates", "pasta", "fr"),
    ("poisson", "fish", "fr"),
    ("saumon", "salmon, fresh", "fr"),
    ("thon", "tuna, fresh", "fr"),
    ("crevettes", "shrimp", "fr"),
    ("moules", "mussels", "fr"),
    ("viande", "meat", "fr"),
    ("legumes", "vegetables", "fr"),
    ("pomme de terre", "potato", "fr"),
    ("carotte", "carrot", "fr"),
    ("oignon", "onion", "fr"),
    ("ail", "garlic", "fr"),
    ("tomate", "tomato", "fr"),
    ("epinards", "spinach", "fr"),
    ("haricots verts", "green beans", "fr"),
    ("champignon", "mushroom", "fr"),
    ("champignons", "mushroom", "fr"),
    ("salade", "lettuce", "fr"),
    ("concombre", "cucumber", "fr"),
    ("courgette", "zucchini", "fr"),
    ("aubergine", "eggplant", "fr"),
    ("avocat", "avocado", "fr"),
    ("pomme", "apple", "fr"),
    ("poire", "pear", "fr"),
    ("banane", "banana", "fr"),
    ("fraise", "strawberry", "fr"),
    ("fraises", "strawberry", "fr"),
    ("orange", "orange", "fr"),
    ("citron", "lemon", "fr"),
    ("raisin", "grape", "fr"),
    ("raisins secs", "raisin", "fr"),
    ("cerise", "cherry", "fr"),
    ("peche", "peach", "fr"),
    ("abricot", "apricot", "fr"),
    ("noix", "walnuts", "fr"),
    ("amandes", "almonds", "fr"),
    ("noisettes", "hazelnuts", "fr"),
    ("cacahuetes", "peanuts", "fr"),
    ("huile d'olive", "olive oil", "fr"),
    ("huile de tournesol", "sunflower oil", "fr"),
    ("sel", "salt", "fr"),
    ("poivre", "black pepper", "fr"),
    ("sucre", "sugar", "fr"),
    ("miel", "honey", "fr"),
    ("vinaigre", "vinegar", "fr"),
    ("moutarde", "mustard", "fr"),
    ("cafe", "coffee", "fr"),
    ("the", "black tea", "fr"),
    ("vin rouge", "red wine", "fr"),
    ("vin blanc", "white wine", "fr"),
    ("biere", "beer", "fr"),
    ("eau", "water", "fr"),
    ("chocolat", "chocolate", "fr"),
    ("all-purpose flour", "wheat flour", "en"),
    ("plain flour", "wheat flour", "en"),
    ("farine", "wheat flour", "fr"),
    ("persil", "parsley", "fr"),
    ("basilic", "basil", "fr"),
    ("thym", "thyme", "fr"),
    ("romarin", "rosemary", "fr"),
    ("menthe", "mint", "fr"),
    ("ciboulette", "chives", "fr"),
    ("aneth", "dill", "fr"),
    # German translations (also used in Luxembourg)
    ("huhn", "chicken", "de"),
    ("hahnchen", "chicken", "de"),
    ("rindfleisch", "beef, fresh", "de"),
    ("schweinefleisch", "pork, fresh", "de"),
    ("lamm", "lamb", "de"),
    ("kase", "cheese", "de"),
    ("milch", "milk", "de"),
    ("ei", "egg", "de"),
    ("eier", "egg", "de"),
    ("brot", "bread", "de"),
    ("kartoffel", "potato", "de"),
    ("kartoffeln", "potato", "de"),
    ("reis", "rice", "de"),
    ("nudeln", "pasta", "de"),
    ("zucker", "sugar", "de"),
    ("salz", "salt", "de"),
    ("pfeffer", "black pepper", "de"),
    ("honig", "honey", "de"),
    ("wasser", "water", "de"),
    ("kaffee", "coffee", "de"),
    ("tee", "black tea", "de"),
    ("wein", "red wine", "de"),
    ("bier", "beer", "de"),
    ("schinken", "ham", "de"),
    ("speck", "bacon", "de"),
    # Portuguese translations (South African / Lusophone context)
    ("frango", "chicken", "pt"),
    ("carne", "beef, fresh", "pt"),
    ("porco", "pork, fresh", "pt"),
    ("peixe", "fish", "pt"),
    ("arroz", "rice", "pt"),
    ("feijao", "black beans", "pt"),
    ("ovo", "egg", "pt"),
    ("ovos", "egg", "pt"),
    ("leite", "milk", "pt"),
    ("queijo", "cheese", "pt"),
    ("manteiga", "butter", "pt"),
    ("pao", "bread", "pt"),
    ("batata", "potato", "pt"),
    ("tomate", "tomato", "pt"),
    ("cebola", "onion", "pt"),
    ("alho", "garlic", "pt"),
    ("azeite", "olive oil", "pt"),
    ("sal", "salt", "pt"),
    ("acucar", "sugar", "pt"),
    ("cafe", "coffee", "pt"),
]


def load() -> None:
    log.info("Building ingredient aliases")

    with SyncSession() as session:
        # Rebuild from scratch so the script is truly idempotent. The table
        # has no UNIQUE constraint on `alias`, so repeated runs would
        # accumulate duplicate rows (PK is id).
        session.query(IngredientAlias).delete()

        inserted = 0
        skipped = 0
        seen: set[str] = set()

        for alias, canonical, lang in ALIASES:
            alias_lower = alias.strip().lower()
            canonical_lower = canonical.strip().lower()

            # Drop in-list duplicates — first occurrence wins.
            if alias_lower in seen:
                log.debug("Skipping duplicate alias '%s' in source list", alias_lower)
                continue

            # Only insert if the canonical exists in dietary_ingredients.
            exists = (
                session.query(DietaryIngredient).filter_by(canonical_name=canonical_lower).first()
            )
            if not exists:
                log.debug(
                    "Skipping alias '%s' -> '%s': canonical name not found",
                    alias_lower,
                    canonical_lower,
                )
                skipped += 1
                continue

            session.add(
                IngredientAlias(
                    alias=alias_lower,
                    canonical_name=canonical_lower,
                    language=lang,
                )
            )
            seen.add(alias_lower)
            inserted += 1

    log.info(
        "Alias build complete: %d inserted, %d skipped (canonical not found)",
        inserted,
        skipped,
    )


if __name__ == "__main__":
    load()
