"""baseline

Revision ID: 5c4881e51b04
Revises:
Create Date: 2026-05-16 17:34:22.582603

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5c4881e51b04"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_sessions_token"), "auth_sessions", ["token"], unique=True)
    op.create_table(
        "dietary_ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("histamine_score", sa.Integer(), nullable=True),
        sa.Column("fodmap_oligos", sa.String(), nullable=True),
        sa.Column("fodmap_fructose", sa.String(), nullable=True),
        sa.Column("fodmap_polyols", sa.String(), nullable=True),
        sa.Column("fodmap_lactose", sa.String(), nullable=True),
        sa.Column("contains_gluten", sa.Boolean(), nullable=False),
        sa.Column("contains_dairy", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("source_version", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_name"),
    )
    op.create_table(
        "entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("entry_time", sa.DateTime(), nullable=True),
        sa.Column("period_of_day", sa.String(), nullable=True),
        sa.Column("overall", sa.Integer(), nullable=False),
        sa.Column("bloating", sa.Integer(), nullable=False),
        sa.Column("stool_normal", sa.Boolean(), nullable=True),
        sa.Column("stool_type", sa.String(), nullable=True),
        sa.Column("stool_status", sa.String(), nullable=True),
        sa.Column("bristol_type", sa.Integer(), nullable=True),
        sa.Column("joint_pain", sa.Integer(), nullable=False),
        sa.Column("neuro", sa.Integer(), nullable=False),
        sa.Column("sleep_quality", sa.Integer(), nullable=False),
        sa.Column("stress", sa.Integer(), nullable=False),
        sa.Column("diet_risk", sa.String(), nullable=False),
        sa.Column("supplements", sa.String(), nullable=False),
        sa.Column("sick", sa.Boolean(), nullable=False),
        sa.Column("hot_shower", sa.Boolean(), nullable=False),
        sa.Column("alcohol_units", sa.Integer(), nullable=True),
        sa.Column("caffeine_servings", sa.Integer(), nullable=True),
        sa.Column(
            "symptoms_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_table(
        "health_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("hrv_mean", sa.Float(), nullable=True),
        sa.Column("hrv_std", sa.Float(), nullable=True),
        sa.Column("resting_hr", sa.Float(), nullable=True),
        sa.Column("sleep_hours", sa.Float(), nullable=True),
        sa.Column("sleep_deep_min", sa.Float(), nullable=True),
        sa.Column("sleep_rem_min", sa.Float(), nullable=True),
        sa.Column("sleep_core_min", sa.Float(), nullable=True),
        sa.Column("sleep_awake_min", sa.Float(), nullable=True),
        sa.Column("sleep_deep_pct", sa.Float(), nullable=True),
        sa.Column("sleep_rem_pct", sa.Float(), nullable=True),
        sa.Column("sleep_efficiency", sa.Float(), nullable=True),
        sa.Column("sleep_start", sa.String(), nullable=True),
        sa.Column("sleep_end", sa.String(), nullable=True),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.Column("active_minutes", sa.Float(), nullable=True),
        sa.Column("spo2", sa.Float(), nullable=True),
        sa.Column("wrist_temp_deviation", sa.Float(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_health_metrics_date"), "health_metrics", ["date"], unique=True)
    op.create_table(
        "lab_marker_catalog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("common_units", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lab_marker_catalog_canonical_name"),
        "lab_marker_catalog",
        ["canonical_name"],
        unique=True,
    )
    op.create_table(
        "labs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lab_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("lab_location", sa.String(), nullable=True),
        sa.Column("source_path", sa.String(), nullable=True),
        sa.Column("source_kind", sa.String(), nullable=False),
        sa.Column("attachment_path", sa.String(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("extraction_model", sa.String(), nullable=True),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("review_status", sa.String(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_labs_lab_date"), "labs", ["lab_date"], unique=False)
    op.create_index(op.f("ix_labs_source_path"), "labs", ["source_path"], unique=False)
    op.create_table(
        "supplement_catalog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("first_used_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_supplement_catalog_key"), "supplement_catalog", ["key"], unique=True)
    op.create_table(
        "symptom_catalog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("first_used_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_symptom_catalog_key"), "symptom_catalog", ["key"], unique=True)
    op.create_table(
        "treatments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("normalized_name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("dose", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_treatments_normalized_name"),
        "treatments",
        ["normalized_name"],
        unique=False,
    )
    op.create_table(
        "weather_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("temperature_c", sa.Float(), nullable=False),
        sa.Column("humidity_pct", sa.Float(), nullable=False),
        sa.Column("pressure_hpa", sa.Float(), nullable=False),
        sa.Column("weather_main", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weather_readings_date"), "weather_readings", ["date"], unique=False)
    op.create_index(
        op.f("ix_weather_readings_timestamp"),
        "weather_readings",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "ingredient_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("canonical_name", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_name"],
            ["dietary_ingredients.canonical_name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lab_marker_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("catalog_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["catalog_id"], ["lab_marker_catalog.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lab_marker_aliases_alias"),
        "lab_marker_aliases",
        ["alias"],
        unique=True,
    )
    op.create_index(
        op.f("ix_lab_marker_aliases_catalog_id"),
        "lab_marker_aliases",
        ["catalog_id"],
        unique=False,
    )
    op.create_table(
        "lab_markers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lab_id", sa.Integer(), nullable=False),
        sa.Column("catalog_id", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("value_text", sa.String(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("ref_low", sa.Float(), nullable=True),
        sa.Column("ref_high", sa.Float(), nullable=True),
        sa.Column("ref_text", sa.String(), nullable=True),
        sa.Column("flag", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["catalog_id"], ["lab_marker_catalog.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["lab_id"], ["labs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_lab_markers_canonical_lab",
        "lab_markers",
        ["canonical_name", "lab_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lab_markers_canonical_name"),
        "lab_markers",
        ["canonical_name"],
        unique=False,
    )
    op.create_index(op.f("ix_lab_markers_lab_id"), "lab_markers", ["lab_id"], unique=False)
    op.create_table(
        "photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("original_filename", sa.String(), nullable=True),
        sa.Column("meal_time", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["entry_id"], ["entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "photo_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("dish_name", sa.String(), nullable=True),
        sa.Column("cuisine", sa.String(), nullable=True),
        sa.Column("dish_confidence", sa.Float(), nullable=True),
        sa.Column("raw_response", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("model_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["photos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("photo_id"),
    )
    op.create_table(
        "photo_ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("canonical_name", sa.String(), nullable=True),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("user_edited", sa.Boolean(), nullable=False),
        sa.Column("histamine_score", sa.Integer(), nullable=True),
        sa.Column("fodmap_oligos", sa.String(), nullable=True),
        sa.Column("fodmap_fructose", sa.String(), nullable=True),
        sa.Column("fodmap_polyols", sa.String(), nullable=True),
        sa.Column("fodmap_lactose", sa.String(), nullable=True),
        sa.Column("contains_gluten", sa.Boolean(), nullable=True),
        sa.Column("contains_dairy", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["photo_analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("photo_ingredients")
    op.drop_table("photo_analyses")
    op.drop_table("photos")
    op.drop_index(op.f("ix_lab_markers_lab_id"), table_name="lab_markers")
    op.drop_index(op.f("ix_lab_markers_canonical_name"), table_name="lab_markers")
    op.drop_index("ix_lab_markers_canonical_lab", table_name="lab_markers")
    op.drop_table("lab_markers")
    op.drop_index(op.f("ix_lab_marker_aliases_catalog_id"), table_name="lab_marker_aliases")
    op.drop_index(op.f("ix_lab_marker_aliases_alias"), table_name="lab_marker_aliases")
    op.drop_table("lab_marker_aliases")
    op.drop_table("ingredient_aliases")
    op.drop_index(op.f("ix_weather_readings_timestamp"), table_name="weather_readings")
    op.drop_index(op.f("ix_weather_readings_date"), table_name="weather_readings")
    op.drop_table("weather_readings")
    op.drop_index(op.f("ix_treatments_normalized_name"), table_name="treatments")
    op.drop_table("treatments")
    op.drop_index(op.f("ix_symptom_catalog_key"), table_name="symptom_catalog")
    op.drop_table("symptom_catalog")
    op.drop_index(op.f("ix_supplement_catalog_key"), table_name="supplement_catalog")
    op.drop_table("supplement_catalog")
    op.drop_index(op.f("ix_labs_source_path"), table_name="labs")
    op.drop_index(op.f("ix_labs_lab_date"), table_name="labs")
    op.drop_table("labs")
    op.drop_index(op.f("ix_lab_marker_catalog_canonical_name"), table_name="lab_marker_catalog")
    op.drop_table("lab_marker_catalog")
    op.drop_index(op.f("ix_health_metrics_date"), table_name="health_metrics")
    op.drop_table("health_metrics")
    op.drop_table("entries")
    op.drop_table("dietary_ingredients")
    op.drop_index(op.f("ix_auth_sessions_token"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    # ### end Alembic commands ###
