from __future__ import annotations

from decimal import Decimal
from typing import Optional, TypedDict

BI_MARKER_REF = "VEL-BI-V1"
BI_PACK_NOTES_PREFIX = "VEL-BI-V1"


class SupplierSpec(TypedDict):
    key: str
    name: str
    default_currency: str


class CustomerSpec(TypedDict):
    name: str
    customer_type: str
    price_tier: str
    phone: str
    email: str
    vat_number: Optional[str]
    billing_address: str


class SkuSpec(TypedDict):
    our_ref: str
    name: str
    design: str
    fabric: str
    category: str
    retail_ex: str
    photo: str
    supplier_key: str
    role: str
    supplier_ref: str
    lead_days: int


BI_SUPPLIERS: list[SupplierSpec] = [
    {"key": "poliform", "name": "Poliform Southern Africa", "default_currency": "EUR"},
    {"key": "bbitalia", "name": "B&B Italia Johannesburg", "default_currency": "EUR"},
    {"key": "cassina", "name": "Cassina Agency SA", "default_currency": "EUR"},
    {"key": "flexform", "name": "Flexform Sandton", "default_currency": "EUR"},
    {"key": "natuzzi", "name": "Natuzzi Italia Gauteng", "default_currency": "EUR"},
    {"key": "ethnicraft", "name": "Ethnicraft Africa", "default_currency": "ZAR"},
    {"key": "roche", "name": "Roche Bobois Hyde Park", "default_currency": "EUR"},
    {"key": "linea", "name": "Linea Pietra Imports", "default_currency": "EUR"},
    {"key": "kramlight", "name": "Kramerville Lighting Co", "default_currency": "ZAR"},
    {"key": "patio", "name": "Patio Lifestyle Trade", "default_currency": "ZAR"},
    {"key": "weylandts", "name": "Weylandts Contract", "default_currency": "ZAR"},
    {"key": "dstore", "name": "Design Store Africa", "default_currency": "ZAR"},
]


BI_CUSTOMERS: list[CustomerSpec] = [
    {
        "name": "Lerato Molefe",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0824112001",
        "email": "lerato.molefe@example.com",
        "vat_number": None,
        "billing_address": "12 4th Ave, Melville, Johannesburg",
    },
    {
        "name": "Johan Botha",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0832201102",
        "email": "johan.botha@example.com",
        "vat_number": None,
        "billing_address": "88 Rietfontein Rd, Primrose, Germiston",
    },
    {
        "name": "Ayesha Khan",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0728803303",
        "email": "ayesha.khan@example.com",
        "vat_number": None,
        "billing_address": "5 Fricker Rd, Illovo, Johannesburg",
    },
    {
        "name": "Sipho Nkosi",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0715404404",
        "email": "sipho.nkosi@example.com",
        "vat_number": None,
        "billing_address": "19 Grant Ave, Norwood, Johannesburg",
    },
    {
        "name": "Annelie du Plessis",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0829905505",
        "email": "annelie.duplessis@example.com",
        "vat_number": None,
        "billing_address": "3 Seventh St, Linden, Johannesburg",
    },
    {
        "name": "Thabo Maseko",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0763106606",
        "email": "thabo.maseko@example.com",
        "vat_number": None,
        "billing_address": "44 Jan Smuts Ave, Parktown North, Johannesburg",
    },
    {
        "name": "Priya Naidoo",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0836707707",
        "email": "priya.naidoo@example.com",
        "vat_number": None,
        "billing_address": "21 Cumberland Rd, Kensington, Johannesburg",
    },
    {
        "name": "Willem Kruger",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0821408808",
        "email": "willem.kruger@example.com",
        "vat_number": None,
        "billing_address": "9 Dely Rd, Waterkloof, Pretoria",
    },
    {
        "name": "Nomsa Khumalo",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0712209909",
        "email": "nomsa.khumalo@example.com",
        "vat_number": None,
        "billing_address": "16 Rivonia Rd, Morningside, Sandton",
    },
    {
        "name": "Daniel Cohen",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0834011010",
        "email": "daniel.cohen@example.com",
        "vat_number": None,
        "billing_address": "7 3rd Ave, Parkhurst, Johannesburg",
    },
    {
        "name": "Fatima Patel",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0725111111",
        "email": "fatima.patel@example.com",
        "vat_number": None,
        "billing_address": "28 Main Rd, Bryanston, Sandton",
    },
    {
        "name": "Pieter Smit",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0826121212",
        "email": "pieter.smit@example.com",
        "vat_number": None,
        "billing_address": "4 Club Ave, Waterkloof Ridge, Pretoria",
    },
    {
        "name": "Zanele Dlamini",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0767131313",
        "email": "zanele.dlamini@example.com",
        "vat_number": None,
        "billing_address": "11 Oxford Rd, Saxonwold, Johannesburg",
    },
    {
        "name": "Ryan van der Merwe",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0838141414",
        "email": "ryan.vdm@example.com",
        "vat_number": None,
        "billing_address": "6 Bedfordview Village, Bedfordview",
    },
    {
        "name": "Karabo Molefe",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0719151515",
        "email": "karabo.molefe@example.com",
        "vat_number": None,
        "billing_address": "2 Victoria Ave, Bruma, Johannesburg",
    },
    {
        "name": "Elize Venter",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0820161616",
        "email": "elize.venter@example.com",
        "vat_number": None,
        "billing_address": "15 Lynnwood Rd, Brooklyn, Pretoria",
    },
    {
        "name": "Mpho Radebe",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0721171717",
        "email": "mpho.radebe@example.com",
        "vat_number": None,
        "billing_address": "8 7th St, Linden, Johannesburg",
    },
    {
        "name": "Sarah Bloom",
        "customer_type": "retail",
        "price_tier": "standard",
        "phone": "0832181818",
        "email": "sarah.bloom@example.com",
        "vat_number": None,
        "billing_address": "31 4th Ave, Parktown North, Johannesburg",
    },
    {
        "name": "Maboneng Studio CC",
        "customer_type": "trade",
        "price_tier": "trade",
        "phone": "0118802101",
        "email": "accounts@mabonengstudio.example.com",
        "vat_number": "4120001001",
        "billing_address": "44 Fox St, Maboneng, Johannesburg",
    },
    {
        "name": "Pretoria North Interiors",
        "customer_type": "trade",
        "price_tier": "trade",
        "phone": "0125412202",
        "email": "books@ptanorthint.example.com",
        "vat_number": "4120001002",
        "billing_address": "102 Rachel de Beer St, Pretoria North",
    },
    {
        "name": "Sandton Atelier Projects",
        "customer_type": "trade",
        "price_tier": "trade",
        "phone": "0117832303",
        "email": "projects@sandtonatelier.example.com",
        "vat_number": "4120001003",
        "billing_address": "Sandton City Office Tower, Sandton",
    },
    {
        "name": "Parkhurst Design Co",
        "customer_type": "trade",
        "price_tier": "trade",
        "phone": "0114472404",
        "email": "studio@parkhurstdesign.example.com",
        "vat_number": "4120001004",
        "billing_address": "21 4th Ave, Parkhurst, Johannesburg",
    },
    {
        "name": "Waterkloof House & Home",
        "customer_type": "trade",
        "price_tier": "trade",
        "phone": "0123462505",
        "email": "orders@waterkloofhh.example.com",
        "vat_number": "4120001005",
        "billing_address": "271 Dely Rd, Waterkloof, Pretoria",
    },
    {
        "name": "Melville Loft Styling",
        "customer_type": "trade",
        "price_tier": "trade",
        "phone": "0114822606",
        "email": "hello@melvilleloft.example.com",
        "vat_number": "4120001006",
        "billing_address": "9 7th St, Melville, Johannesburg",
    },
    {
        "name": "Midrand Contract Furnishers",
        "customer_type": "trade",
        "price_tier": "trade",
        "phone": "0113152707",
        "email": "ap@midrandcf.example.com",
        "vat_number": "4120001007",
        "billing_address": "16 New Rd, Midrand",
    },
    {
        "name": "Fourways Living Studio",
        "customer_type": "trade",
        "price_tier": "trade",
        "phone": "0114652808",
        "email": "accounts@fourwaysliving.example.com",
        "vat_number": "4120001008",
        "billing_address": "The Design Quarter, Fourways",
    },
    {
        "name": "Rosebank Interior House",
        "customer_type": "trade",
        "price_tier": "trade",
        "phone": "0114472909",
        "email": "trade@rosebankih.example.com",
        "vat_number": "4120001009",
        "billing_address": "The Mall of Rosebank, Johannesburg",
    },
    {
        "name": "Centurion Home Projects",
        "customer_type": "trade",
        "price_tier": "trade",
        "phone": "0126633010",
        "email": "ops@centurionhp.example.com",
        "vat_number": "4120001010",
        "billing_address": "1199 South St, Centurion",
    },
    {
        "name": "Illovo Boutique Residences",
        "customer_type": "trade",
        "price_tier": "trade",
        "phone": "0112683111",
        "email": "ff@illovoboutique.example.com",
        "vat_number": "4120001011",
        "billing_address": "Oxford Parks, Illovo, Johannesburg",
    },
    {
        "name": "Menlyn Interior Atelier",
        "customer_type": "trade",
        "price_tier": "trade",
        "phone": "0123483212",
        "email": "studio@menlynatelier.example.com",
        "vat_number": "4120001012",
        "billing_address": "Menlyn Maine, Pretoria",
    },
    {
        "name": "Observatory Craft Interiors",
        "customer_type": "trade",
        "price_tier": "trade",
        "phone": "0116483313",
        "email": "hello@obsycraft.example.com",
        "vat_number": "4120001013",
        "billing_address": "18 Louis Botha Ave, Observatory, Johannesburg",
    },
    {
        "name": "Bryanston Trade Rooms",
        "customer_type": "trade",
        "price_tier": "trade",
        "phone": "0114633414",
        "email": "accounts@bryanstontr.example.com",
        "vat_number": "4120001014",
        "billing_address": "Bryanston Shopping Centre, Sandton",
    },
]


def _sku(
    our_ref: str,
    name: str,
    design: str,
    fabric: str,
    category: str,
    retail_ex: str,
    photo: str,
    supplier_key: str,
    role: str,
    supplier_ref: str,
    lead_days: int,
) -> SkuSpec:
    return {
        "our_ref": our_ref,
        "name": name,
        "design": design,
        "fabric": fabric,
        "category": category,
        "retail_ex": retail_ex,
        "photo": photo,
        "supplier_key": supplier_key,
        "role": role,
        "supplier_ref": supplier_ref,
        "lead_days": lead_days,
    }


BI_SKUS: list[SkuSpec] = [
    # Seating — sofas / sectionals (marker is first)
    _sku(
        BI_MARKER_REF,
        "Verona sectional",
        "Verona sectional",
        "Performance linen sand",
        "Seating",
        "98500.00",
        "bi-sofa-01.jpg",
        "poliform",
        "overstock",
        "PF-VERONA-SEC",
        90,
    ),
    _sku(
        "VEL-BI-SOF-02",
        "Bergamo 3-seater",
        "Bergamo",
        "Sage Belgian linen",
        "Seating",
        "68900.00",
        "bi-sofa-02.jpg",
        "poliform",
        "fast",
        "PF-BERGAMO-3S",
        75,
    ),
    _sku(
        "VEL-BI-SOF-03",
        "Lecce modular corner",
        "Lecce modular",
        "Ivory bouclé",
        "Seating",
        "112000.00",
        "bi-sofa-03.jpg",
        "bbitalia",
        "overstock",
        "BB-LECCE-C",
        100,
    ),
    _sku(
        "VEL-BI-SOF-04",
        "Torino leather 3-seater",
        "Torino",
        "Aniline leather cognac",
        "Seating",
        "124500.00",
        "bi-sofa-04.jpg",
        "cassina",
        "overstock",
        "CA-TORINO-3S",
        110,
    ),
    _sku(
        "VEL-BI-SOF-05",
        "Parma deep-seat",
        "Parma deep",
        "Charcoal performance weave",
        "Seating",
        "54500.00",
        "bi-sofa-05.jpg",
        "natuzzi",
        "fast",
        "NA-PARMA-DS",
        60,
    ),
    _sku(
        "VEL-BI-SOF-06",
        "Siena 2-seater",
        "Siena compact",
        "Blush velvet",
        "Seating",
        "42900.00",
        "bi-sofa-06.jpg",
        "roche",
        "normal",
        "RB-SIENA-2S",
        80,
    ),
    _sku(
        "VEL-BI-SOF-07",
        "Ravenna chaise",
        "Ravenna chaise",
        "Moss velvet",
        "Seating",
        "51900.00",
        "bi-acc-03.jpg",
        "flexform",
        "normal",
        "FX-RAVENNA-CH",
        85,
    ),
    _sku(
        "VEL-BI-SOF-08",
        "Udine lounge",
        "Udine lounge",
        "Walnut taupe weave",
        "Seating",
        "47900.00",
        "bi-sofa-09.jpg",
        "flexform",
        "dead",
        "FX-UDINE-LG",
        85,
    ),
    _sku(
        "VEL-BI-SOF-09",
        "Treviso curved sofa",
        "Treviso arc",
        "Ivory bouclé curve",
        "Seating",
        "62900.00",
        "bi-sofa-11.jpg",
        "roche",
        "normal",
        "RB-TREVISO-ARC",
        90,
    ),
    _sku(
        "VEL-BI-SOF-10",
        "Vicenza club sofa",
        "Vicenza club",
        "Tobacco leather",
        "Seating",
        "79900.00",
        "bi-sofa-12.jpg",
        "cassina",
        "normal",
        "CA-VICENZA-CL",
        95,
    ),
    _sku(
        "VEL-BI-SOF-11",
        "Padova linen 3-seater",
        "Padova",
        "Natural linen stone",
        "Seating",
        "55900.00",
        "bi-sofa-10.jpg",
        "natuzzi",
        "fast",
        "NA-PADOVA-3S",
        55,
    ),
    _sku(
        "VEL-BI-SOF-12",
        "Livorno modular 4-seat",
        "Livorno cloud",
        "Performance cream",
        "Seating",
        "86500.00",
        "bi-sofa-13.jpg",
        "poliform",
        "overstock",
        "PF-LIVORNO-4",
        100,
    ),
    _sku(
        "VEL-BI-SOF-13",
        "Perugia slipcover sofa",
        "Perugia slip",
        "Washe linen ecru",
        "Seating",
        "38900.00",
        "bi-sofa-14.jpg",
        "weylandts",
        "cheap",
        "WY-PERUGIA-SL",
        35,
    ),
    _sku(
        "VEL-BI-SOF-14",
        "Trento compact 2-seater",
        "Trento compact",
        "Graphite weave",
        "Seating",
        "33500.00",
        "bi-sofa-15.jpg",
        "dstore",
        "fast",
        "DS-TRENTO-2S",
        40,
    ),
    _sku(
        "VEL-BI-SOF-15",
        "Bolzano leather lounge",
        "Bolzano",
        "Black saddle leather",
        "Seating",
        "145000.00",
        "bi-sofa-16.jpg",
        "bbitalia",
        "steep",
        "BB-BOLZANO-LL",
        120,
    ),
    _sku(
        "VEL-BI-SOF-16",
        "Modena family sofa",
        "Modena family",
        "Sand linen",
        "Seating",
        "49900.00",
        "bi-sofa-17.jpg",
        "natuzzi",
        "fast",
        "NA-MODENA-FAM",
        50,
    ),
    _sku(
        "VEL-BI-SOF-17",
        "Rimini last-season sofa",
        "Rimini LS",
        "Teal velvet leftover",
        "Seating",
        "29500.00",
        "bi-sofa-18.jpg",
        "dstore",
        "dead",
        "DS-RIMINI-LS",
        45,
    ),
    _sku(
        "VEL-BI-SOF-18",
        "Ancona L-shape",
        "Ancona L",
        "Putty performance",
        "Seating",
        "72900.00",
        "bi-sofa-19.jpg",
        "poliform",
        "normal",
        "PF-ANCONA-L",
        80,
    ),
    _sku(
        "VEL-BI-SOF-19",
        "Pescara daybed",
        "Pescara day",
        "Olive linen",
        "Seating",
        "36500.00",
        "bi-sofa-21.jpg",
        "ethnicraft",
        "dead",
        "ET-PESCARA-DB",
        40,
    ),
    _sku(
        "VEL-BI-SOF-20",
        "Salerno 3-seater",
        "Salerno",
        "Warm grey weave",
        "Seating",
        "44900.00",
        "bi-sofa-22.jpg",
        "natuzzi",
        "fast",
        "NA-SALERNO-3S",
        55,
    ),
    _sku(
        "VEL-BI-SOF-21",
        "Bari bouclé 2-seater",
        "Bari bouclé",
        "Oatmeal bouclé",
        "Seating",
        "41500.00",
        "bi-sofa-24.jpg",
        "roche",
        "normal",
        "RB-BARI-2S",
        70,
    ),
    _sku(
        "VEL-BI-SOF-22",
        "Catania sectional XL",
        "Catania XL",
        "Cloud white performance",
        "Seating",
        "138000.00",
        "bi-acc-08.jpg",
        "bbitalia",
        "overstock",
        "BB-CATANIA-XL",
        120,
    ),
    # Dining chairs
    _sku(
        "VEL-BI-DCH-01",
        "Asti dining chair",
        "Asti chair",
        "Walnut + taupe leather",
        "Dining",
        "8900.00",
        "bi-chair-01.jpg",
        "ethnicraft",
        "fast",
        "ET-ASTI-CH",
        30,
    ),
    _sku(
        "VEL-BI-DCH-02",
        "Alba dining chair",
        "Alba chair",
        "Oak + cream bouclé",
        "Dining",
        "7900.00",
        "bi-chair-02.jpg",
        "ethnicraft",
        "fast",
        "ET-ALBA-CH",
        30,
    ),
    _sku(
        "VEL-BI-DCH-03",
        "Barolo dining chair",
        "Barolo chair",
        "Black oak + oxblood leather",
        "Dining",
        "9800.00",
        "bi-chair-03.jpg",
        "cassina",
        "normal",
        "CA-BAROLO-CH",
        55,
    ),
    _sku(
        "VEL-BI-DCH-04",
        "Chianti side chair",
        "Chianti chair",
        "Ash + sage linen",
        "Dining",
        "6400.00",
        "bi-chair-04.jpg",
        "weylandts",
        "fast",
        "WY-CHIANTI-CH",
        25,
    ),
    _sku(
        "VEL-BI-DCH-05",
        "Stellenbosch dining chair",
        "Stellenbosch chair",
        "Cape oak + charcoal fabric",
        "Dining",
        "7200.00",
        "bi-chair-05.jpg",
        "dstore",
        "fast",
        "DS-STELLEN-CH",
        21,
    ),
    _sku(
        "VEL-BI-DCH-06",
        "Franschhoek carver",
        "Franschhoek carver",
        "Oak + camel leather",
        "Dining",
        "11200.00",
        "bi-chair-06.jpg",
        "ethnicraft",
        "normal",
        "ET-FRANSCH-CV",
        35,
    ),
    _sku(
        "VEL-BI-DCH-07",
        "Constantia dining chair",
        "Constantia chair",
        "Mahogany + ivory linen",
        "Dining",
        "8600.00",
        "bi-chair-07.jpg",
        "weylandts",
        "normal",
        "WY-CONST-CH",
        28,
    ),
    _sku(
        "VEL-BI-DCH-08",
        "Kramerville stool chair",
        "Kramerville stool",
        "Black steel + saddle hide",
        "Dining",
        "4500.00",
        "bi-chair-08.jpg",
        "dstore",
        "cheap",
        "DS-KRAM-ST",
        14,
    ),
    _sku(
        "VEL-BI-DCH-09",
        "Milano cane chair",
        "Milano cane",
        "Teak + natural cane",
        "Dining",
        "6900.00",
        "club-chair.jpg",
        "linea",
        "dead",
        "LP-MILANO-CN",
        50,
    ),
    _sku(
        "VEL-BI-DCH-10",
        "Como bentwood chair",
        "Como bentwood",
        "Walnut bentwood",
        "Dining",
        "5400.00",
        "bi-acc-05.jpg",
        "cassina",
        "fast",
        "CA-COMO-BW",
        40,
    ),
    _sku(
        "VEL-BI-DCH-11",
        "Parkhurst dining chair",
        "Parkhurst chair",
        "White oak + oatmeal",
        "Dining",
        "6100.00",
        "bi-dining-01.jpg",
        "weylandts",
        "fast",
        "WY-PARK-CH",
        21,
    ),
    _sku(
        "VEL-BI-DCH-12",
        "Sandton host chair",
        "Sandton host",
        "Velvet emerald + oak",
        "Dining",
        "12800.00",
        "bi-dining-02.jpg",
        "roche",
        "steep",
        "RB-SAND-HOST",
        70,
    ),
    # Dining tables
    _sku(
        "VEL-BI-DTB-01",
        "Asti oak dining table 240",
        "Asti table 240",
        "Solid European oak",
        "Dining",
        "42900.00",
        "bi-dining-03.jpg",
        "ethnicraft",
        "fast",
        "ET-ASTI-240",
        45,
    ),
    _sku(
        "VEL-BI-DTB-02",
        "Alba round dining table",
        "Alba round",
        "White oak + stone",
        "Dining",
        "36500.00",
        "bi-dining-04.jpg",
        "ethnicraft",
        "normal",
        "ET-ALBA-RD",
        45,
    ),
    _sku(
        "VEL-BI-DTB-03",
        "Barolo walnut table 280",
        "Barolo table 280",
        "Dark walnut slab",
        "Dining",
        "68900.00",
        "bi-dining-05.jpg",
        "cassina",
        "overstock",
        "CA-BAROLO-280",
        80,
    ),
    _sku(
        "VEL-BI-DTB-04",
        "Stellenbosch farm table",
        "Stellenbosch farm",
        "Reclaimed Cape oak",
        "Dining",
        "28900.00",
        "bi-dining-06.jpg",
        "weylandts",
        "fast",
        "WY-STEL-FARM",
        30,
    ),
    _sku(
        "VEL-BI-DTB-05",
        "Franschhoek extendable",
        "Franschhoek ext",
        "Oak veneer extendable",
        "Dining",
        "31900.00",
        "bi-dining-07.jpg",
        "dstore",
        "normal",
        "DS-FRANSCH-EX",
        35,
    ),
    _sku(
        "VEL-BI-DTB-06",
        "Constantia marble table",
        "Constantia marble",
        "Carrara marble + brass",
        "Dining",
        "87500.00",
        "bi-dining-08.jpg",
        "linea",
        "steep",
        "LP-CONST-MAR",
        90,
    ),
    _sku(
        "VEL-BI-DTB-07",
        "Parkhurst 8-seater",
        "Parkhurst 8",
        "Smoked oak",
        "Dining",
        "39900.00",
        "bi-dining-12.jpg",
        "ethnicraft",
        "fast",
        "ET-PARK-8",
        40,
    ),
    _sku(
        "VEL-BI-DTB-08",
        "Melville compact table",
        "Melville compact",
        "Ash whitewash",
        "Dining",
        "18900.00",
        "bi-dining-09.jpg",
        "dstore",
        "cheap",
        "DS-MELV-CMP",
        18,
    ),
    _sku(
        "VEL-BI-DTB-09",
        "Waterkloof glass table",
        "Waterkloof glass",
        "Tempered glass + chrome",
        "Dining",
        "24500.00",
        "bi-dining-10.jpg",
        "dstore",
        "dead",
        "DS-WATER-GL",
        40,
    ),
    _sku(
        "VEL-BI-DTB-10",
        "Illovo ceramic table",
        "Illovo ceramic",
        "Ceramic sintered stone",
        "Dining",
        "45900.00",
        "bi-table-06.jpg",
        "linea",
        "normal",
        "LP-ILLOVO-CER",
        60,
    ),
    # Beds
    _sku(
        "VEL-BI-BED-01",
        "Lucca king bed",
        "Lucca king",
        "Upholstered oatmeal linen",
        "Bedroom",
        "38900.00",
        "bi-bed-01.jpg",
        "natuzzi",
        "fast",
        "NA-LUCCA-K",
        50,
    ),
    _sku(
        "VEL-BI-BED-02",
        "Siena queen bed",
        "Siena queen",
        "Blush velvet headboard",
        "Bedroom",
        "32500.00",
        "bi-bed-02.jpg",
        "roche",
        "normal",
        "RB-SIENA-Q",
        55,
    ),
    _sku(
        "VEL-BI-BED-03",
        "Como platform king",
        "Como platform",
        "Walnut platform + beige",
        "Bedroom",
        "44500.00",
        "bi-bed-03.jpg",
        "poliform",
        "normal",
        "PF-COMO-PK",
        70,
    ),
    _sku(
        "VEL-BI-BED-04",
        "Karoo oak bed",
        "Karoo oak",
        "Solid oak slatted",
        "Bedroom",
        "24900.00",
        "bi-bed-04.jpg",
        "ethnicraft",
        "fast",
        "ET-KAROO-K",
        30,
    ),
    _sku(
        "VEL-BI-BED-05",
        "Drakensberg storage bed",
        "Drakensberg store",
        "White oak storage base",
        "Bedroom",
        "27900.00",
        "bi-bed-06.jpg",
        "weylandts",
        "fast",
        "WY-DRAK-ST",
        28,
    ),
    _sku(
        "VEL-BI-BED-06",
        "Winelands four-poster",
        "Winelands poster",
        "Teak four-poster",
        "Bedroom",
        "56500.00",
        "bi-bed-07.jpg",
        "linea",
        "dead",
        "LP-WINE-4P",
        75,
    ),
    _sku(
        "VEL-BI-BED-07",
        "Sandton winged king",
        "Sandton wing",
        "Charcoal velvet wings",
        "Bedroom",
        "41900.00",
        "bi-bed-08.jpg",
        "natuzzi",
        "normal",
        "NA-SAND-WG",
        50,
    ),
    _sku(
        "VEL-BI-BED-08",
        "Brooklyn low bed",
        "Brooklyn low",
        "Black metal + oak",
        "Bedroom",
        "16900.00",
        "bi-bed-09.jpg",
        "dstore",
        "cheap",
        "DS-BROOK-LW",
        16,
    ),
    _sku(
        "VEL-BI-BED-09",
        "Waterkloof upholstered",
        "Waterkloof uph",
        "Ivory linen king",
        "Bedroom",
        "35900.00",
        "bi-bed-10.jpg",
        "roche",
        "normal",
        "RB-WATER-UPH",
        60,
    ),
    _sku(
        "VEL-BI-BED-10",
        "Menlyn rattan bed",
        "Menlyn rattan",
        "Rattan headboard natural",
        "Bedroom",
        "21500.00",
        "bi-bed-11.jpg",
        "weylandts",
        "dead",
        "WY-MENLYN-RT",
        35,
    ),
    _sku(
        "VEL-BI-BED-11",
        "Hyde Park leather bed",
        "Hyde Park leather",
        "Tobacco leather king",
        "Bedroom",
        "78900.00",
        "bi-bed-12.jpg",
        "cassina",
        "steep",
        "CA-HYDE-LTH",
        90,
    ),
    _sku(
        "VEL-BI-BED-12",
        "Parktown queen",
        "Parktown queen",
        "Sage linen upholstered",
        "Bedroom",
        "28900.00",
        "bi-acc-04.jpg",
        "natuzzi",
        "fast",
        "NA-PARK-Q",
        45,
    ),
    # Outdoor
    _sku(
        "VEL-BI-OUT-01",
        "Clifton sling sofa",
        "Clifton sling",
        "Teak + taupe sling",
        "Outdoor",
        "45900.00",
        "bi-out-01.jpg",
        "patio",
        "fast",
        "PL-CLIFTON-SF",
        40,
    ),
    _sku(
        "VEL-BI-OUT-02",
        "Hermanus teak dining",
        "Hermanus teak",
        "Grade-A teak 8-seater",
        "Outdoor",
        "38900.00",
        "bi-out-02.jpg",
        "patio",
        "fast",
        "PL-HERM-DIN",
        40,
    ),
    _sku(
        "VEL-BI-OUT-03",
        "Plett lounge set",
        "Plett lounge",
        "All-weather wicker sand",
        "Outdoor",
        "32900.00",
        "bi-out-03.jpg",
        "patio",
        "normal",
        "PL-PLETT-LG",
        35,
    ),
    _sku(
        "VEL-BI-OUT-04",
        "Camps Bay daybed",
        "Camps Bay day",
        "Teak + white olefin",
        "Outdoor",
        "27500.00",
        "bi-out-04.jpg",
        "patio",
        "normal",
        "PL-CAMPS-DB",
        35,
    ),
    _sku(
        "VEL-BI-OUT-05",
        "Knysna dining chairs pair",
        "Knysna pair",
        "Teak stacking chairs",
        "Outdoor",
        "8900.00",
        "bi-out-05.jpg",
        "patio",
        "fast",
        "PL-KNYSNA-PR",
        25,
    ),
    _sku(
        "VEL-BI-OUT-06",
        "Umhlanga sun lounger",
        "Umhlanga lounge",
        "Aluminium + mesh",
        "Outdoor",
        "12500.00",
        "bi-out-06.jpg",
        "patio",
        "fast",
        "PL-UMHL-SL",
        25,
    ),
    _sku(
        "VEL-BI-OUT-07",
        "Hartbeespoort leftover set",
        "Harties leftover",
        "Last-season lime olefin",
        "Outdoor",
        "14900.00",
        "bi-out-09.jpg",
        "dstore",
        "dead",
        "DS-HART-LS",
        30,
    ),
    _sku(
        "VEL-BI-OUT-08",
        "Magaliesberg bar set",
        "Magalies bar",
        "Acacia bar table + stools",
        "Outdoor",
        "18900.00",
        "bi-acc-07.jpg",
        "weylandts",
        "dead",
        "WY-MAGAL-BAR",
        30,
    ),
    _sku(
        "VEL-BI-OUT-09",
        "Ballito rope sofa",
        "Ballito rope",
        "Rope weave + teak",
        "Outdoor",
        "36500.00",
        "outdoor-teak.jpg",
        "patio",
        "normal",
        "PL-BALL-RP",
        40,
    ),
    _sku(
        "VEL-BI-OUT-10",
        "Irene outdoor dining",
        "Irene dining",
        "Powder-coat aluminium",
        "Outdoor",
        "22900.00",
        "bi-stor-01.jpg",
        "patio",
        "normal",
        "PL-IRENE-DN",
        30,
    ),
    _sku(
        "VEL-BI-OUT-11",
        "Bryanston fire table",
        "Bryanston fire",
        "Concrete + teak surround",
        "Outdoor",
        "41900.00",
        "bi-stor-02.jpg",
        "linea",
        "steep",
        "LP-BRYAN-FIRE",
        70,
    ),
    _sku(
        "VEL-BI-OUT-12",
        "Fourways parasol",
        "Fourways parasol",
        "3.5m cantilever taupe",
        "Outdoor",
        "8900.00",
        "bi-stor-03.jpg",
        "patio",
        "cheap",
        "PL-FOUR-PAR",
        20,
    ),
    # Coffee / side tables
    _sku(
        "VEL-BI-CTB-01",
        "Carrara nest pair",
        "Carrara nest",
        "White marble nests",
        "Tables",
        "18900.00",
        "marble-coffee.jpg",
        "linea",
        "fast",
        "LP-CARR-NEST",
        40,
    ),
    _sku(
        "VEL-BI-CTB-02",
        "Travertine coffee table",
        "Travertine coffee",
        "Roman travertine",
        "Tables",
        "24500.00",
        "bi-table-02.jpg",
        "linea",
        "normal",
        "LP-TRAV-CF",
        50,
    ),
    _sku(
        "VEL-BI-CTB-03",
        "Oak drum coffee table",
        "Oak drum",
        "Solid oak drum",
        "Tables",
        "12900.00",
        "bi-table-03.jpg",
        "ethnicraft",
        "fast",
        "ET-OAK-DRM",
        25,
    ),
    _sku(
        "VEL-BI-CTB-04",
        "Walnut side table",
        "Walnut side",
        "American walnut",
        "Tables",
        "7900.00",
        "bi-table-04.jpg",
        "ethnicraft",
        "fast",
        "ET-WAL-SIDE",
        25,
    ),
    _sku(
        "VEL-BI-CTB-05",
        "Brass drinks table",
        "Brass drinks",
        "Antique brass tray",
        "Tables",
        "6400.00",
        "bi-table-07.jpg",
        "kramlight",
        "fast",
        "KL-BRASS-DR",
        20,
    ),
    _sku(
        "VEL-BI-CTB-06",
        "Concrete coffee block",
        "Concrete block",
        "Fibre concrete grey",
        "Tables",
        "9800.00",
        "bi-table-08.jpg",
        "dstore",
        "normal",
        "DS-CONC-BLK",
        22,
    ),
    _sku(
        "VEL-BI-CTB-07",
        "Glass waterfall table",
        "Glass waterfall",
        "12mm glass waterfall",
        "Tables",
        "15900.00",
        "bi-acc-01.jpg",
        "dstore",
        "dead",
        "DS-GLASS-WF",
        35,
    ),
    _sku(
        "VEL-BI-CTB-08",
        "Rattan side table",
        "Rattan side",
        "Natural rattan drum",
        "Tables",
        "3900.00",
        "bi-acc-02.jpg",
        "weylandts",
        "cheap",
        "WY-RATT-SIDE",
        14,
    ),
    _sku(
        "VEL-BI-CTB-09",
        "Pietra coffee oval",
        "Pietra oval",
        "Emperador marble oval",
        "Tables",
        "32500.00",
        "bi-acc-06.jpg",
        "linea",
        "overstock",
        "LP-PIETRA-OV",
        60,
    ),
    _sku(
        "VEL-BI-CTB-10",
        "Parkhurst nesting trio",
        "Parkhurst nest",
        "Black steel + oak",
        "Tables",
        "8900.00",
        "bi-acc-09.jpg",
        "dstore",
        "fast",
        "DS-PARK-NEST",
        18,
    ),
    _sku(
        "VEL-BI-CTB-11",
        "Sandton console",
        "Sandton console",
        "Travertine console 160",
        "Tables",
        "28900.00",
        "bi-acc-10.jpg",
        "linea",
        "normal",
        "LP-SAND-CON",
        55,
    ),
    _sku(
        "VEL-BI-CTB-12",
        "Linden live-edge table",
        "Linden live",
        "Live-edge kiaat",
        "Tables",
        "21900.00",
        "walnut-lounge.jpg",
        "weylandts",
        "normal",
        "WY-LIND-LE",
        30,
    ),
    # Lighting
    _sku(
        "VEL-BI-LMP-01",
        "Arco floor lamp",
        "Arco floor",
        "Marble base + steel arc",
        "Decor",
        "18900.00",
        "bi-lamp-01.jpg",
        "kramlight",
        "fast",
        "KL-ARCO-FL",
        25,
    ),
    _sku(
        "VEL-BI-LMP-02",
        "Fontana table lamp",
        "Fontana table",
        "Opaline glass",
        "Decor",
        "8900.00",
        "bi-lamp-02.jpg",
        "kramlight",
        "fast",
        "KL-FONT-TB",
        20,
    ),
    _sku(
        "VEL-BI-LMP-03",
        "Castiglioni pendant",
        "Castiglioni pend",
        "Spun aluminium pendant",
        "Decor",
        "12500.00",
        "bi-lamp-03.jpg",
        "kramlight",
        "normal",
        "KL-CAST-PD",
        30,
    ),
    _sku(
        "VEL-BI-LMP-04",
        "Kramerville tripod lamp",
        "Kram tripod",
        "Black tripod + linen shade",
        "Decor",
        "4500.00",
        "bi-lamp-04.jpg",
        "kramlight",
        "fast",
        "KL-KRAM-TRI",
        14,
    ),
    _sku(
        "VEL-BI-LMP-05",
        "Murano cluster pendant",
        "Murano cluster",
        "Amber Murano glass",
        "Decor",
        "24500.00",
        "bi-lamp-06.jpg",
        "linea",
        "steep",
        "LP-MURANO-CL",
        70,
    ),
    _sku(
        "VEL-BI-LMP-06",
        "Paper lantern trio",
        "Paper lantern",
        "Rice paper shades",
        "Decor",
        "2900.00",
        "bi-lamp-07.jpg",
        "dstore",
        "cheap",
        "DS-PAPER-TRI",
        10,
    ),
    _sku(
        "VEL-BI-LMP-07",
        "Brass picture light",
        "Brass picture",
        "Antique brass 600mm",
        "Decor",
        "3900.00",
        "bi-lamp-08.jpg",
        "kramlight",
        "fast",
        "KL-BRASS-PIC",
        14,
    ),
    _sku(
        "VEL-BI-LMP-08",
        "Alabaster wall sconce pair",
        "Alabaster sconce",
        "Alabaster + brass",
        "Decor",
        "9800.00",
        "bi-acc-12.jpg",
        "kramlight",
        "normal",
        "KL-ALA-SC",
        25,
    ),
    _sku(
        "VEL-BI-LMP-09",
        "Overberg rattan pendant",
        "Overberg rattan",
        "Large rattan dome",
        "Decor",
        "5400.00",
        "bi-acc-13.jpg",
        "weylandts",
        "fast",
        "WY-OVER-RAT",
        18,
    ),
    _sku(
        "VEL-BI-LMP-10",
        "Last-season chrome floor",
        "Chrome leftover",
        "High-chrome leftover",
        "Decor",
        "3200.00",
        "bi-sofa-01.jpg",
        "dstore",
        "dead",
        "DS-CHROME-FL",
        20,
    ),
    _sku(
        "VEL-BI-LMP-11",
        "Parkhurst ceramic lamp",
        "Parkhurst ceramic",
        "Speckled ceramic + linen",
        "Decor",
        "4200.00",
        "london-3s.jpg",
        "kramlight",
        "fast",
        "KL-PARK-CER",
        16,
    ),
    _sku(
        "VEL-BI-LMP-12",
        "Sandton chandelier 12-light",
        "Sandton chand",
        "Brass 12-light ring",
        "Decor",
        "38900.00",
        "chesterfield.jpg",
        "linea",
        "overstock",
        "LP-SAND-CH12",
        80,
    ),
    # Accessories
    _sku(
        "VEL-BI-ACC-01",
        "Kilim floor cushion",
        "Kilim cushion",
        "Vintage kilim 90cm",
        "Decor",
        "1900.00",
        "bi-acc-03.jpg",
        "weylandts",
        "fast",
        "WY-KILIM-FC",
        10,
    ),
    _sku(
        "VEL-BI-ACC-02",
        "Mohair throw sand",
        "Mohair throw",
        "Karoo mohair sand",
        "Decor",
        "2400.00",
        "linen-lshape.jpg",
        "dstore",
        "fast",
        "DS-MOHAIR-SD",
        10,
    ),
    _sku(
        "VEL-BI-ACC-03",
        "Murano amber vase",
        "Murano vase",
        "Hand-blown amber",
        "Decor",
        "4500.00",
        "ivory-curve.jpg",
        "linea",
        "fast",
        "LP-MURANO-VS",
        25,
    ),
    _sku(
        "VEL-BI-ACC-04",
        "Travertine bowl",
        "Travertine bowl",
        "Carved travertine",
        "Decor",
        "3200.00",
        "modular-cloud.jpg",
        "linea",
        "fast",
        "LP-TRAV-BWL",
        20,
    ),
    _sku(
        "VEL-BI-ACC-05",
        "Ceramic vessel set",
        "Ceramic vessels",
        "Stoneware trio",
        "Decor",
        "1800.00",
        "sand-modular.jpg",
        "dstore",
        "fast",
        "DS-CER-SET",
        12,
    ),
    _sku(
        "VEL-BI-ACC-06",
        "Walnut tray",
        "Walnut tray",
        "Solid walnut serving",
        "Decor",
        "1600.00",
        "velvet-chaise.jpg",
        "ethnicraft",
        "fast",
        "ET-WAL-TRAY",
        14,
    ),
    _sku(
        "VEL-BI-ACC-07",
        "Leather ottoman cube",
        "Leather cube",
        "Saddle leather 45cm",
        "Seating",
        "6900.00",
        "charcoal-deep.jpg",
        "natuzzi",
        "normal",
        "NA-LTH-CUBE",
        30,
    ),
    _sku(
        "VEL-BI-ACC-08",
        "Mirror sunburst 120",
        "Sunburst mirror",
        "Brass sunburst 120cm",
        "Decor",
        "8900.00",
        "boucle-2s.jpg",
        "kramlight",
        "normal",
        "KL-SUN-120",
        25,
    ),
    _sku(
        "VEL-BI-ACC-09",
        "Last-season neon sculpture",
        "Neon leftover",
        "Pink neon word art",
        "Decor",
        "2200.00",
        "bi-sofa-02.jpg",
        "dstore",
        "dead",
        "DS-NEON-WD",
        20,
    ),
    _sku(
        "VEL-BI-ACC-10",
        "Alpaca throw charcoal",
        "Alpaca throw",
        "Peruvian alpaca charcoal",
        "Decor",
        "3100.00",
        "bi-sofa-05.jpg",
        "weylandts",
        "fast",
        "WY-ALPACA-CH",
        12,
    ),
    _sku(
        "VEL-BI-ACC-11",
        "Marble bookends pair",
        "Marble bookends",
        "Carrara bookends",
        "Decor",
        "2400.00",
        "bi-sofa-06.jpg",
        "linea",
        "fast",
        "LP-MARB-BK",
        18,
    ),
    _sku(
        "VEL-BI-ACC-12",
        "Woven wall hanging",
        "Woven hanging",
        "Handwoven wool 140cm",
        "Decor",
        "4800.00",
        "bi-sofa-09.jpg",
        "weylandts",
        "dead",
        "WY-WOVEN-WH",
        20,
    ),
    # Storage
    _sku(
        "VEL-BI-STO-01",
        "Verona sideboard 200",
        "Verona sideboard",
        "Oak + smoked glass",
        "Storage",
        "38900.00",
        "bi-stor-01.jpg",
        "poliform",
        "normal",
        "PF-VERONA-SB",
        70,
    ),
    _sku(
        "VEL-BI-STO-02",
        "Bergamo dresser",
        "Bergamo dresser",
        "Walnut 6-drawer",
        "Storage",
        "32500.00",
        "bi-stor-02.jpg",
        "cassina",
        "normal",
        "CA-BERG-DR",
        65,
    ),
    _sku(
        "VEL-BI-STO-03",
        "Kramerville bookcase",
        "Kram bookcase",
        "Black steel + oak shelves",
        "Storage",
        "14900.00",
        "bi-stor-03.jpg",
        "dstore",
        "fast",
        "DS-KRAM-BK",
        21,
    ),
    _sku(
        "VEL-BI-STO-04",
        "Ethnicraft TV unit",
        "Ethnicraft TV",
        "Solid oak media unit",
        "Storage",
        "18900.00",
        "bi-dining-01.jpg",
        "ethnicraft",
        "fast",
        "ET-TV-180",
        30,
    ),
    _sku(
        "VEL-BI-STO-05",
        "Parkhurst tallboy",
        "Parkhurst tall",
        "White oak 5-drawer",
        "Storage",
        "16500.00",
        "bi-dining-05.jpg",
        "weylandts",
        "normal",
        "WY-PARK-TB",
        25,
    ),
    _sku(
        "VEL-BI-STO-06",
        "Leftover high-gloss cabinet",
        "Gloss leftover",
        "High-gloss white 2019",
        "Storage",
        "9900.00",
        "bi-dining-08.jpg",
        "dstore",
        "dead",
        "DS-GLOSS-CAB",
        30,
    ),
]


EUR_SUPPLIER_KEYS = frozenset(
    {"poliform", "bbitalia", "cassina", "flexform", "natuzzi", "roche", "linea"}
)
LOCAL_SUPPLIER_KEYS = frozenset({"ethnicraft", "kramlight", "patio", "weylandts", "dstore"})


def sku_barcode(index: int) -> str:
    return f"600124{index:07d}"


def lead_days_for(supplier_key: str, category: str) -> int:
    """Canonical lead time: Italy/EU 6–14 weeks, local SA freight 2–5 weeks."""
    if supplier_key in EUR_SUPPLIER_KEYS:
        if category in ("Seating", "Bedroom"):
            return 90
        if category in ("Dining", "Tables", "Storage"):
            return 75
        return 49
    if category == "Decor":
        return 14
    if category == "Outdoor":
        return 28
    return 21


def qty_for_role(role: str) -> tuple[int, int, int]:
    """Return (po_receive_qty, transfer_to_showroom, till_sell_qty).

    Every on-hand or sold unit comes from a PO receive at Kramerville.
    ``transfer_to_showroom <= po_receive_qty`` and ``till_sell_qty <= transfer``.
    """
    if role == "fast":
        return 12, 6, 1
    if role == "dead":
        return 8, 0, 0
    if role == "overstock":
        return 7, 1, 0
    if role == "cheap":
        return 8, 4, 1
    if role == "steep":
        return 4, 2, 0
    return 6, 3, 0


def pricing_for_role(retail_ex: Decimal, role: str) -> tuple[Decimal, Decimal]:
    """Return (wholesale_ex, unit_cost). Markup ~2–2.5x except outliers."""
    if role == "cheap":
        unit_cost = (retail_ex / Decimal("1.20")).quantize(Decimal("0.01"))
        wholesale = (retail_ex * Decimal("0.95")).quantize(Decimal("0.01"))
        return wholesale, unit_cost
    if role == "steep":
        unit_cost = (retail_ex / Decimal("4.20")).quantize(Decimal("0.01"))
        wholesale = (retail_ex * Decimal("0.55")).quantize(Decimal("0.01"))
        return wholesale, unit_cost
    markup = {
        "fast": Decimal("2.30"),
        "dead": Decimal("2.20"),
        "overstock": Decimal("2.45"),
        "normal": Decimal("2.35"),
    }[role]
    unit_cost = (retail_ex / markup).quantize(Decimal("0.01"))
    wholesale = (retail_ex * Decimal("0.70")).quantize(Decimal("0.01"))
    if role == "dead":
        # one inverted-price style: wholesale close to retail (mis-ticketed)
        wholesale = (retail_ex * Decimal("0.92")).quantize(Decimal("0.01"))
    return wholesale, unit_cost


def po_waves(role: str) -> list[tuple[int, int]]:
    """Split PO qty into (qty, receive_days_ago) waves so stock ages vary.

    Receive is always after order+lead (stamped in the pack from lead_days_for).
    Fast movers get an old container plus a later replenishment.
    """
    po_qty, _transfer, _sell = qty_for_role(role)
    if role == "dead":
        return [(po_qty, 260)]
    if role == "overstock":
        return [(po_qty, 210)]
    if role == "fast":
        replenish = min(4, po_qty - 1)
        return [(po_qty - replenish, 250), (replenish, 85)]
    if role == "cheap":
        return [(po_qty, 140)]
    return [(po_qty, 170)]


for _spec in BI_SKUS:
    _spec["lead_days"] = lead_days_for(_spec["supplier_key"], _spec["category"])
